In [202]:
import pandas as pd

In [203]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [204]:
from array import array

In [205]:
a = array('i', [1, 2, 3, 4, 5])
a.typecode
a.itemsize

4

In [206]:
# Diferença entre listas e arrays
from array import array
from sys import getsizeof

In [207]:
l = list(range(1_000_000))
a = array('i', l)

In [208]:
getsizeof(l)


8000056

In [209]:
getsizeof(a)

4000064

In [210]:
from numpy import array

In [211]:
a = array([1, 2, 3, 4, 5])
a.dtype

dtype('int64')

In [212]:
a*2
a/3
a*2+1/2

array([ 2.5,  4.5,  6.5,  8.5, 10.5])

In [213]:
a.min()
a.max()

5

In [214]:
a = array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
    ])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [215]:
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [216]:
from pandas import DataFrame

In [217]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [218]:
df = DataFrame(l, columns='A B C'.split())
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [219]:
df['A']
df.A

0    1
1    4
2    7
Name: A, dtype: int64

In [220]:
df = DataFrame(l, columns='A B C'.split(), index='Linha1 Linha2 Linha3'.split())
df

A  B  C
Linha1  1  2  3
Linha2  4  5  6
Linha3  7  8  9

In [221]:
from pandas import Series

In [222]:
df = DataFrame(l, columns='A B C'.split(), index='Linha1 Linha2 Linha3'.split())
df = df['A']
df


Linha1    1
Linha2    4
Linha3    7
Name: A, dtype: int64

In [223]:
s = Series(df)
s

Linha1    1
Linha2    4
Linha3    7
Name: A, dtype: int64

In [224]:
s.apply(lambda x: x**2)
s.apply(lambda x: str(x)*3)
s.apply(lambda x: bool(x))
s.apply(bool)

Linha1    True
Linha2    True
Linha3    True
Name: A, dtype: bool

In [225]:
s.map({1: 'um', 4: 'quatro', 7: 'sete'})

Linha1        um
Linha2    quatro
Linha3      sete
Name: A, dtype: object

In [226]:
from pandas import DataFrame

In [227]:
d = {
    'Eduardo': [1, 2, 3, 4, 5],
    'Maria': [6, 7, 8, 9, 10],
    'João': [11, 12, 13, 14, 15]
    }
df = DataFrame(d)
df

Eduardo  Maria  João
0        1      6    11
1        2      7    12
2        3      8    13
3        4      9    14
4        5     10    15

In [228]:
# df['Eduardo']
# type(df['Eduardo'])
# s = df.iloc[:]
s = df
s

Eduardo  Maria  João
0        1      6    11
1        2      7    12
2        3      8    13
3        4      9    14
4        5     10    15

In [229]:
s1 = s['Eduardo'].apply(lambda x: str(x)*3)
s1
s2 = s['Maria'].apply(lambda x: str(x)*3)
s2
s3 = s['João'].apply(lambda x: str(x)*3)
s3
s0 = pd.concat([s1, s2, s3], axis=1)
s0

Eduardo   Maria    João
0     111     666  111111
1     222     777  121212
2     333     888  131313
3     444     999  141414
4     555  101010  151515

In [230]:
# df['Eduardo'] = df['Eduardo'].apply(lambda x: int(str(x).zfill(6)[:3]))
df

Eduardo  Maria  João
0        1      6    11
1        2      7    12
2        3      8    13
3        4      9    14
4        5     10    15

In [242]:
df['Eduardo_1'] = df.João.apply(lambda x: int(str(x).zfill(1)*3))
df
type(df['Eduardo_1'])
# https://youtu.be/GhKVR72eJmA?t=6533
# hEff-1222

pandas.core.series.Series